import SavedTrip from '../models/SavedTrip.js';
import { generateEmbedding, buildTripSummary } from './embedding.js';
import { ingestTripKnowledge } from '../vector/services/trip-knowledge.service.js';
import type { Itinerary } from '../types/itinerary.js';

/**
 * Saving a generated itinerary as a real SavedTrip, in one place.
 *
 * Three call sites needed this and only one of them did it completely: the
 * REST create path embedded the trip AND ingested it into the vector layer,
 * while the agent's own trip-planning pipeline did neither — so agent-planned
 * trips were saved but invisible to both search bars and to RAG. Anything that
 * persists a trip goes through here now, so a fourth caller can't reintroduce
 * the same gap.
 *
 * `indexTrip` is fire-and-forget by design: the trip is already durably saved
 * by the time it runs, and a failed embedding must never cost a user their
 * itinerary. It is exported so callers that want to await indexing (tests) can.
 */

export interface SaveItineraryOptions {
  title?: string;
  description?: string;
  startDate?: string | Date;
  travelType?: string;
  travelers?: number;
  budgetTotal?: number;
  tags?: string[];
  source?: string;
}

/** Default budget split, in percent, matching budgetMode 'capped'. */
const DEFAULT_BUDGET_SPLIT = { travel: 25, accommodation: 30, food: 20, events: 25 };

export async function indexTrip(tripDoc: any, userId: string): Promise<void> {
  const plain = typeof tripDoc.toObject === 'function' ? tripDoc.toObject() : tripDoc;
  try {
    const summary = buildTripSummary(plain);
    const embedding = await generateEmbedding(summary);
    await SavedTrip.updateOne({ _id: tripDoc._id }, { $set: { embedding, searchSummary: summary } });
  } catch (err: any) {
    console.error(`Embedding trip ${tripDoc._id} failed (search will miss it): ${err.message}`);
  }
  try {
    await ingestTripKnowledge(tripDoc, userId);
  } catch (err: any) {
    console.error(`Vector ingestion for trip ${tripDoc._id} failed (RAG will miss it): ${err.message}`);
  }
}

/**
 * Persist a generated Itinerary. Returns the saved document.
 *
 * The Itinerary type and the SavedTrip schema disagree on two names —
 * `travelers` vs the schema's required `numberOfPeople`, and `duration` vs
 * `totalDays` — so the mapping is done here rather than at each call site,
 * where getting it wrong fails schema validation at write time only.
 */
export async function saveItineraryAsTrip(
  userId: string,
  itinerary: Itinerary | any,
  options: SaveItineraryOptions = {},
): Promise<any> {
  const meta = itinerary?.tripMetadata || {};
  const destination: string = options.title ? options.title : meta.destination || 'Trip';
  const days: number = meta.duration || itinerary?.days?.length || 1;
  const travelers = options.travelers ?? meta.travelers ?? meta.numberOfPeople ?? 1;
  const travelType = options.travelType || meta.travelType || 'leisure';
  const budgetTotal = options.budgetTotal ?? Number(meta.budget?.total ?? meta.budget) ?? 0;

  const startDate = options.startDate
    ? new Date(options.startDate)
    : meta.startDate
      ? new Date(meta.startDate)
      : new Date();

  const trip = await SavedTrip.create({
    user: userId,
    title: options.title || `${days}-day ${travelType} trip to ${meta.destination || destination}`,
    description: options.description || `Generated by the TravelTea agent.`,
    startDate,
    cities: [{ name: meta.destination || destination, days }],
    totalDays: days,
    people: travelers,
    travelType,
    budget: {
      total: Number.isFinite(budgetTotal) ? budgetTotal : 0,
      ...DEFAULT_BUDGET_SPLIT,
      mode: 'capped',
    },
    budgetMode: 'capped',
    generatedItinerary: {
      days: itinerary.days,
      tripMetadata: {
        destination: meta.destination || destination,
        numberOfPeople: travelers,
        travelers,
        budget: { perDay: days > 0 ? Math.round((budgetTotal || 0) / days) : 0 },
      },
    },
    tags: options.tags || [travelType, meta.destination || destination, options.source || 'agent-planned'],
  });

  void indexTrip(trip, userId);
  return trip;
}
